### ISSUE TITLE
Update due to Angular 2.0 beta release

### ISSUE THREAD

**Issue by livingmine** [joeeames/AngularJSDirectivesFundamentals#1]
Hi,

I guess this course needs an update as i guess directives are treated differently on Angular 2.0 beta. Simple notification for students to not use angular 2.0 on their plunkr might be sufficient. Great Course!

**Comment by joeeames** [comment]
This is an Angular 1 course. It really has nothing to do with Angular 2. Angular 2 is not an upgrade to Angular 1, it's an entirely different product. But this course still has plenty of value as-is because Angular 1 will be used in production for many years to come. I'm going to close this issue, but thanks for commenting.
